### ISSUE TITLE
Exception Cannot read property 'lbParam' of undefined

### ISSUE THREAD

**Issue by JoaoSouMoreira** [flyingfisher/selenium-html-js-converter#13]
Hey, very useful tool by the way! I was trying out the example code on your `README.md` file to execute this with wd-sync and got the exception stated in the title. Since the converted test suite expects two parameters (`_browser` and `_options`), I think you should either change the example to reflect that or add a check for `_options` around line `1218` on `JavascriptFormatter.js` and around line `1332` on `JavascriptFormatter.ts`. I did the checking myself and that seems to fix it. I can create a pull request with this if needed.

**Comment by flyingfisher** [comment]
Yes, this is a problem.
Miss some guard code in selenium-utils.js.
Fixed in version 0.4.7.
Thanks
