### ISSUE TITLE
Command values containing "<br />" are incorrectly formatted

### ISSUE THREAD

**Issue by JoaoSouMoreira** [flyingfisher/selenium-html-js-converter#17]
While trying to convert from HTML to JS, any command with a value containing the tag `<br />` is going to result in an incorrectly escaped string for `currentCommand`.

For example:
```
type("id=some-input", "Hello <br />World")
```
Will convert to:
```
"currentCommand= 'type("id=some-input", "Hello
World")';
```

I am thinking the command value needs to be processed by `xLateArgument()` or it needs to add a `.replace(/\n/g, '\\n')` to command.value in line `134` of `JavascriptFormatter.js` to re-escape the command's value.

Let me know what you think!

Once again I appreciate your work on this tool, really great.

**Comment by flyingfisher** [comment]
Sorry for late reply.
I have fixed error, using ```.replace(/\n/g, '\\n')```.
Thanks for finding that issue.
