### ISSUE TITLE
typo in Readme

### ISSUE THREAD

**Issue by mattimatti** [flyingfisher/selenium-html-js-converter#2]
/phatomjs default wd port

browser.init({browserName: 'phatomjs'});

**Comment by flyingfisher** [comment]
Sorry, I do not understand what you mean. Could you speak a little more or just tell me what is right. :)

**Comment by mattimatti** [comment]
Hello, it's the spelling of the word "phatomjs", should be "phantomjs" :)

**Comment by flyingfisher** [comment]
Fixed. Thanks a lot. ;)
